### ISSUE TITLE
Adding a new item throws PushFailedException

### ISSUE THREAD

**Issue by winnicki** [Azure-Samples/app-service-mobile-xamarin-android-quickstart#6]
I'm using this sample in conjunction with https://github.com/Azure-Samples/app-service-mobile-dotnet-backend-quickstart. The only updates I made are:

1. Update all NuGet packages (both solutions)
2. Point to my backend, add keys for authentication
3. Commented out anything to do with push notifications in both solutions. Here is my updated PostTodoItem (left the commented code out for brevity):

```
// TodoItemController
public async Task<IHttpActionResult> PostTodoItem(TodoItem item)
        {
            TodoItem current = await InsertAsync(item);
            if (current != null)
                return Ok();

            return Content(System.Net.HttpStatusCode.InternalServerError, current);
}
```

4. Added Application Insights to inspect error messages and which endpoints are being hit

So basically if you just update all packages and comment out push notifications (or leave them in since you have them configured already) we should be using the same versions. 

Authentication with Facebook, refreshing items, adding, and completing items is **all working except that I'm always getting push failed error messages**. I'm getting these messages _even though_ when I look directly in the database the data in the TodoItems table is correct. What's more is that when I inspect the error messages through Application Insights, I don't actually see the TodoItemController.PatchTodoItem getting hit -- only the PostTodoItem. 

It seems like as though the Azure.Mobile.Client is sending posts instead of patches but that seems absurd because that would mean it's severely broken.

The other frustration is I don't know to debug this any further. If you have any tips on how I can please let me know. 

I'm hoping if you test this solution on your side that you will see the same issues and then we can go from there. 

Thanks!

**Comment by winnicki** [comment]
I just noticed that for the connection string, MultipleActiveResultsSets was set to False when publishing the back end. I set it to true and I'm testing now. Perhaps that is the issue.

**Comment by winnicki** [comment]
That didn't fix the issue.

**Comment by winnicki** [comment]
Microsoft.WindowsAzure.MobileServices.Sync.MobileServicePushFailedException:

<img width="1273" alt="screen shot 2017-02-23 at 10 48 10 am" src="https://cloud.githubusercontent.com/assets/4955058/23273926/c504e8ba-f9b5-11e6-86b4-dc50d8709041.png">

Here is a failed push where I launched the app, hit Refresh, and then added this one item. Just inserting the new item fails even though the status code is an OK 200 (!?)

**Comment by winnicki** [comment]
I also noticed during testing that if I just sync items down and update them (as in mark them as completed) I don't receive any errors. Errors only start to occur once you add items.

Still though, in Application Insights I don't see the PATCH getting hit when marking as completed.

**Comment by adrianhall** [comment]
Your POST code is wrong.  You need to return a Created route.  Something like the following is required:

```
        public async Task<IHttpActionResult> PostTodoItem(Green item)
        {
            Green current = await InsertAsync(item);
            return CreatedAtRoute("Tables", new { id = current.Id }, current);
        }
```

**Comment by winnicki** [comment]
Thanks @adrianhall for the prompt response. It did dawn on me that the SDK needs the item back. I updated it to this and it works now but I'll look into your code so that I can use it if needed. 

```
public async Task<TodoItem> PostTodoItem(TodoItem item)
{
     return await InsertAsync(item);
}
```
